enum OperationCode {
  CONNECT,
  CLOSE_CONNECT,
  TURN_ON_POWER,
  TURN_OFF_POWER,
  QUERY_SERIAL_NUMBER,
  READER,
  READER_DATA,
  WRIATE_DATA,
  REGISTER_BROADCAST,
  UNREGISTER_BROADCAST,
  LISTENER_BROADCAST,
  ERROR_CODE,
}