enum RfidOperationFailedCode {
  NOT_SUPPORT_RIFD,
  NOT_CONNECTED,
  NOT_TURN_ON_POWER,
  NOT_APPEAR_OVER,
  QUERY_SERIAL_NUMBER_FAILED,
  READER_OPERATION_FAILED,
  WRITE_DATA_FAILED,
  UNREGISTER_BROADCAST,
  OTHER_FAILED,
}